export default {
  allowPlaceholders: true,
  placeholderPattern: '<待填写(?:[：；][^>]*)?>',
  requiredFiles: [
    'AGENTS.md',
    'docs/PROJECT_PROFILE.md',
    'docs/AI_PROMPT_ENGINEERING.md',
    'docs/AI_TASK_PROMPT.md',
    'docs/AI_PAGE_PROMPT.md',
    'docs/AI_PROJECT_STANDARDS.md',
    'docs/AI_COMPONENT_CATALOG.md',
    'docs/AI_CAPABILITY_REQUIREMENTS.md',
    'docs/AI_ACCEPTANCE_EVIDENCE.md',
    '.agents/skills/project-workflow/SKILL.md',
    '.agents/skills/project-workflow/agents/openai.yaml',
    '.agents/skills/project-workflow/references/task-routing.md',
  ],
  promptContracts: [
    {
      file: 'docs/AI_TASK_PROMPT.md',
      sections: ['目标：', '上下文：', '约束：', '完成条件：'],
    },
    {
      file: 'docs/AI_PAGE_PROMPT.md',
      sections: ['目标：', '上下文：', '约束：', '完成条件：'],
    },
  ],
  projectSkill: {
    name: 'project-workflow',
    path: '.agents/skills/project-workflow/SKILL.md',
    metadataPath: '.agents/skills/project-workflow/agents/openai.yaml',
    maxLines: 500,
    triggerPatterns: ['Use when', '用于.+时', '当.+时使用'],
  },
  routing: {
    path: '.agents/skills/project-workflow/references/task-routing.md',
    requiredMarkers: [
      '$tdd-workflow',
      '$product-design:index',
      '$design-taste-frontend',
      '$frontend-design',
      '$product-design:image-to-code',
      '$figma:figma-use',
      '$figma:figma-create-new-file',
      '$figma:figma-generate-design',
      '$figma:figma-design-to-code',
      '$product-design:audit',
      '$web-design-guidelines',
      '$vercel-react-best-practices',
      '$api-design',
      '$security-review',
      '$browser:control-in-app-browser',
      'GitHub 插件',
    ],
  },
  capabilityRequirements: {
    path: 'docs/AI_CAPABILITY_REQUIREMENTS.md',
    requiredMarkers: [
      'product-design@openai-curated-remote',
      'figma@openai-curated-remote',
      'github@openai-curated-remote',
      'browser@openai-bundled',
      'affaan-m/everything-claude-code',
      'leonxlnx/taste-skill',
      'vercel-labs/agent-skills',
    ],
  },
  forbiddenPatterns: ['digital-oversight-frontend', 'atai-agent-group-digitaloversight'],
  packageIntegration: {
    enabled: true,
    required: false,
    manifestPath: 'package.json',
    aiCheckScript: 'ai:check',
    aiCheckCommand: 'node scripts/check-ai-guidance.mjs',
    qualityScripts: ['check', 'check:ci'],
  },
}
