export default {
  allowPlaceholders: true,
  placeholderPattern: '<待填写(?:[：；][^>]*)?>',
  requiredFiles: [
    'AGENTS.md',
    'docs/PROJECT_PROFILE.md',
    'docs/AI_WORKFLOW_PRINCIPLES.md',
    'docs/AI_TASK_CONTRACT.md',
    'docs/AI_FRONTEND_TASK.md',
    'docs/AI_PROJECT_STANDARDS.md',
    'docs/AI_COMPONENT_CATALOG.md',
    'docs/CODEX_CAPABILITIES.md',
    'docs/AI_ACCEPTANCE_EVIDENCE.md',
    'docs/FRONTEND_CONVENTIONS.md',
    '.codex/manifest.json',
    'docs/capability-state.json',
    '.agents/skills/project-workflow/SKILL.md',
    '.agents/skills/project-workflow/agents/openai.yaml',
    '.agents/skills/project-workflow/references/task-routing.md',
    ...['bootstrap-project', 'frontend-task', 'codex-capability-setup'].flatMap((name) => [
      `.agents/skills/${name}/SKILL.md`,
      `.agents/skills/${name}/agents/openai.yaml`,
    ]),
    ...['profile-selection', 'profile-schema', 'project-creation', 'confirmation-flow', 'merge-policy', 'resource-lifecycle',
      'acceptance-checklist'].map(name => `.agents/skills/bootstrap-project/references/${name}.md`),
    ...['source-routing', 'common-workflow', 'screenshot-workflow', 'prototype-workflow', 'html-workflow',
      'figma-workflow', 'api-workflow', 'requirement-workflow', 'acceptance-matrix']
      .map(name => `.agents/skills/frontend-task/references/${name}.md`),
    ...['setup-phases', 'install-policy', 'verification-checklist', 'status-model']
      .map(name => `.agents/skills/codex-capability-setup/references/${name}.md`),
    '.agents/skills/codex-capability-setup/templates/approval-input.md',
  ],
  promptContracts: [
    {
      file: 'docs/AI_TASK_CONTRACT.md',
      sections: ['目标：', '上下文：', '约束：', '完成条件：'],
    },
    {
      file: 'docs/AI_FRONTEND_TASK.md',
      sections: ['目标：', '上下文：', '约束：', '完成条件：'],
    },
  ],
  projectSkill: {
    name: 'project-workflow',
    path: '.agents/skills/project-workflow/SKILL.md',
    metadataPath: '.agents/skills/project-workflow/agents/openai.yaml',
    maxLines: 500,
    triggerPatterns: ['Use when', '用于.+时', '当.+时使用'],
  },
  routing: {
    path: '.agents/skills/project-workflow/references/task-routing.md',
    requiredMarkers: [
      '$tdd-workflow',
      '$frontend-task',
      '$product-design:index',
      '$frontend-design-direction',
      '$frontend-design',
      '$product-design:image-to-code',
      '$figma:figma-use',
      '$figma:figma-create-new-file',
      '$figma:figma-generate-design',
      '$figma:figma-design-to-code',
      '$product-design:audit',
      '$web-design-guidelines',
      '$vercel-react-best-practices',
      '$api-design',
      '$security-review',
      '$browser:control-in-app-browser',
      'GitHub 插件',
    ],
  },
  capabilityRequirements: {
    path: 'docs/CODEX_CAPABILITIES.md',
    requiredMarkers: [
      'product-design@openai-api-curated',
      'figma@openai-api-curated',
      'github',
      'browser@openai-bundled',
      'affaan-m/everything-claude-code',
      'anthropics/skills',
      'leonxlnx/taste-skill',
      'vercel-labs/agent-skills',
    ],
  },
  forbiddenPatterns: ['digital-oversight-frontend', 'atai-agent-group-digitaloversight'],
  projectRecords: {
    manifest: '.codex/manifest.json',
    capabilities: 'docs/capability-state.json',
  },
  additionalSkills: ['bootstrap-project', 'frontend-task', 'codex-capability-setup'].map((name) => ({
    name,
    path: `.agents/skills/${name}/SKILL.md`,
    metadataPath: `.agents/skills/${name}/agents/openai.yaml`,
    maxLines: 500,
    triggerPatterns: ['Initialize', 'Execute', 'Audit'],
  })),
  packageIntegration: {
    enabled: false,
    required: false,
    manifestPath: 'package.json',
    aiCheckScript: 'ai:check',
    aiCheckCommand: 'node .codex/scripts/check-ai-guidance.mjs --root .',
    qualityScripts: ['check', 'check:ci'],
  },
}
