export default {
  allowPlaceholders: true,
  placeholderPattern: '<待填写(?:[：；][^>]*)?>',
  requiredFiles: [
    'AGENTS.md',
    'docs/PROJECT_PROFILE.md',
    'docs/AI_WORKFLOW_PRINCIPLES.md',
    'docs/AI_TASK_CONTRACT.md',
    'docs/AI_FRONTEND_TASK.md',
    'docs/AI_PROJECT_STANDARDS.md',
    'docs/AI_COMPONENT_CATALOG.md',
    'docs/CODEX_CAPABILITIES.md',
    'docs/AI_ACCEPTANCE_EVIDENCE.md',
    'docs/AI_WEBVIEW_MOBILE.md',
    'docs/AI_COMPATIBILITY_MATRIX.md',
    'docs/FRONTEND_CONVENTIONS.md',
    '.codex/manifest.json',
    '.codex/profile-state.json',
    '.codex/templates/profile-proposal.template.json',
    '.codex/templates/component-catalog.template.md',
    '.codex/templates/component-catalog.presets.json',
    '.codex/templates/component-catalog.generic.md',
    '.codex/templates/component-catalog.react.md',
    '.codex/templates/component-catalog.vue.md',
    'docs/capability-state.json',
    '.agents/skills/project-workflow/SKILL.md',
    '.agents/skills/project-workflow/agents/openai.yaml',
    '.agents/skills/project-workflow/references/task-routing.md',
    '.agents/skills/project-profile/SKILL.md',
    '.agents/skills/project-profile/agents/openai.yaml',
    '.agents/skills/project-profile/references/state-model.md',
    '.agents/skills/project-profile/references/template-selection.md',
    '.agents/skills/project-profile/references/init-workflow.md',
    '.agents/skills/project-profile/references/update-policy.md',
    ...['frontend-task', 'codex-capability-setup'].flatMap((name) => [
      `.agents/skills/${name}/SKILL.md`,
      `.agents/skills/${name}/agents/openai.yaml`,
    ]),
    ...['source-routing', 'common-workflow', 'screenshot-workflow', 'prototype-workflow', 'html-workflow',
      'figma-workflow', 'api-workflow', 'requirement-workflow', 'acceptance-matrix', 'subcommands', 'task-state']
      .map(name => `.agents/skills/frontend-task/references/${name}.md`),
    ...['setup-phases', 'install-policy', 'verification-checklist', 'status-model']
      .map(name => `.agents/skills/codex-capability-setup/references/${name}.md`),
    '.agents/skills/codex-capability-setup/templates/approval-input.md',
  ],
  promptContracts: [
    { file: 'docs/AI_TASK_CONTRACT.md', sections: ['目标：', '上下文：', '约束：', '完成条件：'] },
    { file: 'docs/AI_FRONTEND_TASK.md', sections: ['目标：', '上下文：', '约束：', '完成条件：'] },
  ],
  projectSkill: {
    name: 'project-workflow',
    path: '.agents/skills/project-workflow/SKILL.md',
    metadataPath: '.agents/skills/project-workflow/agents/openai.yaml',
    maxLines: 500,
    triggerPatterns: ['Use when', '用于.+时', '当.+时使用'],
  },
  routing: {
    path: '.agents/skills/project-workflow/references/task-routing.md',
    requiredMarkers: ['$frontend-task', '$project-profile', '$codex-capability-setup', '$tdd-workflow', '$api-design', '$security-review'],
  },
  capabilityRequirements: {
    path: 'docs/CODEX_CAPABILITIES.md',
    requiredMarkers: ['product-design@openai-api-curated', 'figma@openai-api-curated', 'github', 'browser@openai-bundled'],
  },
  forbiddenPatterns: ['digital-oversight-frontend', 'atai-agent-group-digitaloversight', '$bootstrap-project'],
  projectRecords: {
    manifest: '.codex/manifest.json',
    profile: '.codex/profile-state.json',
    capabilities: 'docs/capability-state.json',
  },
  additionalSkills: ['project-profile', 'frontend-task', 'codex-capability-setup'].map((name) => ({
    name,
    path: `.agents/skills/${name}/SKILL.md`,
    metadataPath: `.agents/skills/${name}/agents/openai.yaml`,
    maxLines: 500,
    triggerPatterns: ['Initialize', 'Execute', 'Audit', 'Confirm', 'Update'],
  })),
  packageIntegration: {
    enabled: false,
    required: false,
    manifestPath: 'package.json',
    aiCheckScript: 'ai:check',
    aiCheckCommand: 'node .codex/scripts/check-ai-guidance.mjs --root .',
    qualityScripts: ['check', 'check:ci'],
  },
}
